spring:
  application:
    name: delivery-cost
  config:
    import: "optional:consul:"
  cloud:
    consul:
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 20s
        healthCheckTimeout: 50s

server:
  port: 8100

app:
  default-currency: "EUR"

